name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check code out
        uses: actions/checkout@v4
      - name: Use Node.js 20x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install npm dependencies
        run: npm install
      - name: Execute tests
        run: npm run test:unit
      - name: Softunit username
        run: echo 'g.dzhevelekov'

  build-and-ui-test:
    needs: build-and-unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Check code out
        uses: actions/checkout@v4
      - name: Use Node.js 20x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install npm dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install
      - name: Start the site
        run: npm run start &        
      - name: Execute UI tests  
        run: npm run test:ui
